ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "deliveryAddress1" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "deliveryAddress2" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "deliveryCity" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "deliveryCounty" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "deliveryPostcode" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "deliveryCountry" TEXT;
